package sredis

const (
	CMD_bgrewriteaof    = "BGREWRITEAOF"
	CMD_bgsave          = "BGSAVE"
	CMD_clientgetname   = "CLIENT GETNAME"
	CMD_clientkill      = "CLIENT KILL"
	CMD_clientlist      = "CLIENT LIST"
	CMD_clientpause     = "CLIENT PAUSE"
	CMD_clientsetname   = "CLIENT SETNAME"
	CMD_command         = "COMMAND"
	CMD_commandcount    = "COMMAND COUNT"
	CMD_commandgetkeys  = "COMMAND GETKEYS"
	CMD_commandinfo     = "COMMAND INFO"
	CMD_configget       = "CONFIG GET"
	CMD_configresetstat = "CONFIG RESETSTAT"
	CMD_configrewrite   = "CONFIG REWRITE"
	CMD_configset       = "CONFIG SET"
	CMD_dbsize          = "DBSIZE"
	CMD_debugobject     = "DEBUG OBJECT"
	CMD_debugsegfault   = "DEBUG SEGFAULT"
	CMD_flushall        = "FLUSHALL"
	CMD_flushdb         = "FLUSHDB"
	CMD_info            = "INFO"
	CMD_lastsave        = "LASTSAVE"
	CMD_monitor         = "MONITOR"
	CMD_role            = "ROLE"
	CMD_save            = "SAVE"
	CMD_shutdown        = "SHUTDOWN"
	CMD_slaveof         = "SLAVEOF"
	CMD_slowlog         = "SLOWLOG"
	CMD_sync            = "SYNC"
	CMD_time            = "TIME"
)
